# Generated by Selenium IDE
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestDfTest1(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        driver = webdriver.Chrome()
        # 设置隐式等待30s
        driver.implicitly_wait(30)
        cls.driver = driver

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    def test_menu(self):
        """测试左侧页面点击"""
        self.driver.get("http://df.zhiyitech.cn/login")
        self.driver.set_window_size(1440, 875)
        # 调用登陆模块

        # 点击左侧列表菜单
        self.driver.find_element(By.XPATH, "//span[contains(.,\'抖音选款\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'小红书推荐\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'灵感集\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'小红书达人\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'淘系商品\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'抖音小店\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'商品企划\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'设计任务\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'样衣库\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'出入库记录\')]").click()


if __name__ == '__main__':
    unittest.main()
